kind: Service
apiVersion: v1
metadata:
  name: faktory
spec:
  type: NodePort
  selector:
    app: faktory-server
  ports:
  - name: faktory
    protocol: TCP
    port: 7419
    nodePort: 31419
  - name: dashboard
    protocol: TCP
    port: 7420